{
 "title": "Application Metrics View",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes,service)"
    }
   },
   {
    "name": "api",
    "label": "API",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{service=\"$service\", uri!=\"NOT_FOUND\"},uri)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{service=\"$service\", api=~\"$api\"},method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${service} Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability (1 hour)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(increase(http_server_requests_seconds_count{service=\"$service\", status=~\"5..\"}[1d]) or vector(0)) / sum(increase(http_server_requests_seconds_count{service=\"$service\"}[1d]))))",
     "legendFormat": "Selected Day"
    }
   ]
  },
  {
   "title": "Availability (1 day)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(increase(http_server_requests_seconds_count{service=\"$service\", status=~\"5..\"}[1d]) or vector(0)) / sum(increase(http_server_requests_seconds_count{service=\"$service\"}[1d]))))",
     "legendFormat": "Selected Day"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum(rate(http_server_requests_seconds_count{service=\"$service\", status=~\"5..\"}[2m])) OR on() vector(0)) / sum(rate(http_server_requests_seconds_count{service=\"$service\"}[2m]))",
     "legendFormat": "Selected Day"
    },
    {
     "expr": "1 - sum(rate(http_server_requests_seconds_count{service=\"$service\", status=~\"5..\"}[2m] offset 7d)) / sum(rate(http_server_requests_seconds_count{service=\"$service\"}[2m] offset 7d))",
     "legendFormat": "7 days before"
    }
   ]
  },
  {
   "title": "Availability (7 days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(increase(http_server_requests_seconds_count{service=\"$service\",  status=~\"5..\"}[7d]) or vector(0)) / sum(increase(http_server_requests_seconds_count{service=\"$service\"}[7d]))))",
     "legendFormat": "Selected Day"
    }
   ]
  },
  {
   "title": "Availability (30 days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(increase(http_server_requests_seconds_count{service=\"$service\", status=~\"5..\"}[30d]) or vector(0)) / sum(increase(http_server_requests_seconds_count{service=\"$service\"}[30d]))))",
     "legendFormat": "Selected Day"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Service Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\"}[2m]))",
     "legendFormat": "Selected Day"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\"}[2m] offset 7d))",
     "legendFormat": "7 days before"
    }
   ]
  },
  {
   "title": "API Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\"}[2m])) by (uri, method)",
     "legendFormat": "{{method}} :: {{uri}}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Avg Response Time (Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_seconds_sum{service=\"$service\"}[5m]) > 0) / sum(rate(http_server_requests_seconds_count{service=\"$service\"}[5m]) > 0)",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Avg Response Time (API)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"$service\", uri=~\"$api\", method=~\"$method\", uri!=\"NOT_FOUND\"}[5m]) > 0) by (uri, method) / sum(rate(http_server_requests_seconds_count{service=\"$service\", uri=~\"$api\", method=~\"$method\"}[5m]) > 0) by (uri, method)",
     "legendFormat": "{{method}} :: {{uri}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Service Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\", status=~\"5..\"}[2m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\", method=~\"$method\", status=~\"5..\"}[2m])) by (uri, method, outcome)",
     "legendFormat": "{{method}} :: {{uri}} :: {{outcome}}"
    }
   ]
  }
 ]
}