{
 "title": "JVM Metrics View",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes,service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_uptime_seconds{service=\"$service\" })",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_start_time_seconds{service=\"$service\" }*1000)"
    }
   ]
  },
  {
   "title": "Max Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{service=\"$service\" }",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{service=\"$service\" }",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_states_threads{service=\"$service\",   state=\"blocked\"}",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\",  area=\"heap\"})*100/sum(jvm_memory_max_bytes{service=\"$service\" , area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Active Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_connection_active{service=\"$service\", pod=\"$pod\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total GC Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$service\",  action=\"end of major GC\"}[$__range]))",
     "legendFormat": "Major"
    },
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{service=\"$service\",   action=\"end of minor GC\"}[$__range]))",
     "legendFormat": "Minor"
    }
   ]
  },
  {
   "title": "Max GC Pause",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(jvm_gc_pause_seconds_max{service=\"$service\",  action=\"end of major GC\"})",
     "legendFormat": "Major"
    },
    {
     "expr": "max(jvm_gc_pause_seconds_max{service=\"$service\",   action=\"end of minor GC\"})",
     "legendFormat": "Minor"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\",   area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{service=\"$service\",  area=\"heap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{service=\"$service\",   area=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\",  area=\"nonheap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{service=\"$service\",   area=\"nonheap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{service=\"$service\",   area=\"nonheap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\" })",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{service=\"$service\" })",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{service=\"$service\" })",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_rss_bytes{service=\"$service\" }",
     "legendFormat": "RSS"
    },
    {
     "expr": "process_memory_swap_bytes{service=\"$service\" }",
     "legendFormat": "Swap"
    },
    {
     "expr": "process_memory_rss_bytes{service=\"$service\" } + process_memory_swap_bytes{service=\"$service\" }",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\" }[2m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"$service\",  status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{service=\"$service\",  status!~\"5..\"}[2m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{service=\"$service\",  status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(app_connection_active{service=\"$service\" })",
     "legendFormat": "connection"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\",  status=~\"5..\"}[5m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{service=\"$service\" }[2m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{service=\"$service\" }[1m])/rate(jvm_gc_pause_seconds_count{service=\"$service\" }[1m])",
     "legendFormat": "Avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{service=\"$service\" }",
     "legendFormat": "Max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{service=\"$service\", pod=\"$pod\"}[2m])",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{service=\"$service\", pod=\"$pod\"}[2m])",
     "legendFormat": "Promoted"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": "process_threads{service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Process"
    }
   ]
  },
  { "title": "Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }, "repeat": "persistence_counts" },
  {
   "title": "Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Eden Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Eden Space\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Eden Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Survivor Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Survivor Space\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Survivor Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Old Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Old Gen\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=\"PS Old Gen\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\",pod=\"$pod\",id=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\",pod=\"$pod\",id=\"Metaspace\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\",id=\"Metaspace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CodeHeap - Profiled nmethods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\",pod=\"$pod\",id=\"Compressed Class Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\",pod=\"$pod\",id=\"Compressed Class Space\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\",id=\"Compressed Class Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CodeHeap - Non-profiled nmethods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CodeHeap - Non-nmethods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\",id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "Direct : Used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{service=\"$service\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "Direct : Capacity"
    },
    {
     "expr": "jvm_buffer_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "Mapped : Used"
    },
    {
     "expr": "jvm_buffer_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "Mapped : Used"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{service=\"$service\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "Direct - count"
    },
    {
     "expr": "jvm_buffer_count_buffers{service=\"$service\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "Mapped - count"
    }
   ]
  }
 ]
}