{
 "title": "Support Services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "High JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service) (jvm_memory_used_bytes{service=\"$service\", area=\"heap\"}) * 100\n          /\n          sum by(service)(jvm_memory_max_bytes{service=\"$service\", area=\"heap\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(metrics_executor_memoryUsed_bytes/metrics_executor_memoryTotal_bytes) * 100 or vector(0) ",
     "legendFormat": "{{spark_app_id}}"
    }
   ]
  },
  {
   "title": "Frequent JVM GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service, app) (increase(jvm_gc_pause_seconds_count[10m]))  ",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Low Task Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(\n     sum by (pod_name, namespace, application_name, spark_app_id) (metrics_executor_completedTasks_total)\n     /\n     sum by (pod_name, namespace, application_name, spark_app_id) (metrics_executor_totalTasks_total)\n) * 100  ",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "High Major GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by(service) (increase(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[10m])) or vector(0)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "High Failed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum by (container) (increase(metrics_executor_failedTasks_total[5m]))  ",
     "legendFormat": "{{spark_app_id}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  avg(\n    rate(http_server_requests_seconds_sum{service=\"$service\"}[5m])\n  ) by (service)\n  / \n  sum(\n    rate(http_server_requests_seconds_count{service=\"$service\"}[5m])\n  ) by (service)\n) * 1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Job success Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "100 * (\n  sum by(pod_name, application_name, spark_app_id, job) (rate(metrics_executor_completedTasks_total[5m]))\n  /\n  sum by(pod_name, application_name, spark_app_id, job) (rate(metrics_executor_totalTasks_total[5m]))\n)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[1m]) > 0 or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}