apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-blackbox-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-blackbox-exporter
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          preferred_ip_protocol: ip4
          valid_status_codes: [200]
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          fail_if_body_not_matches_regexp:
            # For Quarkus health checks
            - "UP|DOWN"  # Match either UP or DOWN in the response
            # For standard health checks
            - "Ok|ok"    # Match Ok in any case
            # For version endpoints
            - "version|Version"  # Match version info 