apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-blackbox-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.docker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: blackbox-exporter
          image: {{ .Values.docker.repo }}/blackbox-exporter:v0.24.1
          imagePullPolicy: {{ .Values.docker.pullPolicy }}
          args:
            - --config.file=/config/blackbox.yml
          ports:
            - name: http
              containerPort: 9115
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                  - ALL
    {{- if .Values.blackbox.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.blackbox.nodeSelector | nindent 8 }}
    {{- else if.Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.blackbox.tolerations }}
      tolerations:
        {{- toYaml .Values.blackbox.tolerations | nindent 8 }}
    {{- else if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-blackbox-exporter

 
