{
 "title": "Typesense Metrics View",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(typesense_metrics{key=\"system_cpu_active_percentage\"}[5m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(typesense_metrics{key=\"system_memory_used_bytes\"}) / sum(typesense_metrics{key=\"system_memory_total_bytes\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(typesense_metrics{key=\"system_disk_used_bytes\"}) / sum(typesense_metrics{key=\"system_disk_total_bytes\"}),0.001)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Avg Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(typesense_stats{key=\"total_requests_per_second\"}[5m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(typesense_stats{key=~\".*_latency_ms\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Overall CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(typesense_metrics{key=\"system_cpu_active_percentage\"}[5m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Overall Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(typesense_metrics{key=\"system_memory_used_bytes\"}) / sum(typesense_metrics{key=\"system_memory_total_bytes\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Detailed CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(typesense_metrics{key=~\"system_cpu.*_active_percentage\"}[5m])",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Detailed Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(typesense_metrics{key=\"typesense_memory_active_bytes\"}[5m])",
     "legendFormat": "Active"
    },
    {
     "expr": "avg_over_time(typesense_metrics{key=\"typesense_memory_metadata_bytes\"}[5m])",
     "legendFormat": "Metadata"
    },
    {
     "expr": "avg_over_time(typesense_metrics{key=\"typesense_memory_mapped_bytes\"}[5m])",
     "legendFormat": "Mapped"
    },
    {
     "expr": "avg_over_time(typesense_metrics{key=\"typesense_memory_retained_bytes\"}[5m])",
     "legendFormat": "Retained"
    },
    {
     "expr": "avg_over_time(typesense_metrics{key=\"typesense_memory_resident_bytes\"}[5m])",
     "legendFormat": "Resident"
    },
    {
     "expr": "avg_over_time(typesense_metrics{key=\"typesense_memory_allocated_bytes\"}[5m])",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "round(sum(typesense_metrics{key=\"system_disk_used_bytes\"}) / sum(typesense_metrics{key=\"system_disk_total_bytes\"}),0.001)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(typesense_metrics{key=\"system_network_received_bytes\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "-sum(rate(typesense_metrics{key=\"system_network_sent_bytes\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(typesense_stats{key=\"total_requests_per_second\"}[5m])",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Request Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg_over_time(typesense_stats{key=\"write_requests_per_second\"}[5m])",
       "legendFormat": "Write"
      },
      {
       "expr": "avg_over_time(typesense_stats{key=\"search_requests_per_second\"}[5m])",
       "legendFormat": "Search"
      },
      {
       "expr": "avg_over_time(typesense_stats{key=\"import_requests_per_second\"}[5m])",
       "legendFormat": "Import"
      },
      {
       "expr": "avg_over_time(typesense_stats{key=\"delete_requests_per_second\"}[5m])",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg_over_time(typesense_stats{key=\"overloaded_requests_per_second\"}[5m])",
       "legendFormat": "Overloaded"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Response Time (Service)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(avg_over_time(typesense_stats{key=~\".*_latency_ms\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Avg Response Time (Request)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg_over_time(typesense_stats{key=\"import_latency_ms\"}[5m])",
       "legendFormat": "Import"
      },
      {
       "expr": "avg_over_time(typesense_stats{key=\"search_latency_ms\"}[5m])",
       "legendFormat": "Search"
      },
      {
       "expr": "avg_over_time(typesense_stats{key=\"write_latency_ms\"}[5m])",
       "legendFormat": "Write"
      },
      {
       "expr": "avg_over_time(typesense_stats{key=\"delete_latency_ms\"}[5m])",
       "legendFormat": "Delete"
      }
     ]
    }
   ]
  }
 ]
}