{
 "title": "Kubernetes Cluster View",
 "description": "Global View Dashboard for Kubernetes cluster(s)",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval]))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(rate(windows_cpu_time_total{mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{} - windows_memory_available_bytes{} - windows_memory_cache_bytes{})",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{}- node_filesystem_free_bytes{})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{})",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "CPU  Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval])))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "avg(sum by (core) (rate(windows_cpu_time_total{mode!=\"idle\"}[$__rate_interval])))",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(machine_cpu_cores{})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) / sum(machine_cpu_cores{})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / sum(node_memory_MemTotal_bytes{})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(windows_memory_available_bytes{} + windows_memory_cache_bytes{}) / sum(windows_os_visible_memory_bytes{})",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(machine_memory_bytes{})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) / sum(machine_memory_bytes{})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Disk  Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{}- node_filesystem_free_bytes{})) / sum(node_filesystem_size_bytes{} )",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info{})", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info{})", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info{})", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels{})", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels{})", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels{})", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{})",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels{})", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info{})", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info{})", "legendFormat": "Secrets" },
    {
     "expr": "sum(kube_networkpolicy_labels{})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(count by (node) (kube_node_info{}))",
     "legendFormat": "Nodes"
    },
    {
     "expr": "count(kube_namespace_created{})",
     "legendFormat": "Namespaces"
    }
   ]
  },
  {
   "title": "Pods QoS classes",
   "type": "timeseries",
   "description": "Guaranteed: All containers have matching CPU and memory requests and limits, granting the highest protection from eviction.\n\nBurstable:\nAt least one container has resource requests, but requests and limits don’t match exactly, resulting in medium eviction priority.\n\nBestEffort:\nNo CPU or memory requests/limits, making these pods first in line for eviction under resource pressure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class{}) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    { "expr": "sum(kube_pod_info{})", "legendFormat": "Total pods" }
   ]
  },
  {
   "title": "Pods Status Reason",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Container Restarts by Namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pod OOM Events by Namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Overall CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval])))",
     "legendFormat": "Linux"
    },
    {
     "expr": "1 - avg(rate(windows_cpu_time_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Overall Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / sum(node_memory_MemTotal_bytes{})",
     "legendFormat": "Linux"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{} - windows_memory_available_bytes{}) / sum(windows_os_visible_memory_bytes{})",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "CPU Utilization by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "avg(sum by (instance,core) (rate(windows_cpu_time_total{mode!=\"idle\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) by (instance) / sum(node_memory_MemTotal_bytes{}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{} - windows_memory_available_bytes{}) by (instance) / sum(windows_os_visible_memory_bytes{}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Namespace (Usage/Requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (kubernetes_namespace) \n/ \nsum(label_replace(kube_pod_container_resource_requests{resource=\"cpu\"}, \"kubernetes_namespace\", \"$1\", \"namespace\", \"(.+)\")) by (kubernetes_namespace)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Namespace (Usage/Requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Utilization by Namespace (Usage/Limits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (kubernetes_namespace) \n/ \nsum(label_replace(kube_pod_container_resource_limits{resource=\"cpu\"}, \"kubernetes_namespace\", \"$1\", \"namespace\", \"(.+)\")) by (kubernetes_namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Namespace (Usage/Limits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (kubernetes_namespace) \n/ \nsum(label_replace(kube_pod_container_resource_limits{resource=\"memory\"}, \"kubernetes_namespace\", \"$1\", \"namespace\", \"(.+)\")) by (kubernetes_namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Overall Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_free_bytes{}) / sum(node_filesystem_size_bytes{})",
     "legendFormat": "Disk usage in %"
    }
   ]
  },
  {
   "title": "Throughput(Reads+Writes) by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node_name) (\n  rate(container_fs_reads_merged_total{job=\"cadvisor\",device!~\"^/dev/[sv]d[a-z][0-9]*$\",id=\"/\"}[$__rate_interval])\n  +\n  rate(container_fs_writes_merged_total{job=\"cadvisor\",device!~\"^/dev/[sv]d[a-z][0-9]*$\",id=\"/\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput(Reads+Writes) by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace) (\n  rate(\n    container_fs_reads_bytes_total{job=\"cadvisor\",device=~\"(/dev/)?(mmcblk.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",kubernetes_namespace!=\"\"}[$__rate_interval]\n  )\n+ rate(\n    container_fs_writes_bytes_total{job=\"cadvisor\",device=~\"(/dev/)?(mmcblk.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",kubernetes_namespace!=\"\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Disk Utilization by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_free_bytes{}) by (instance) / sum(node_filesystem_size_bytes{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS(Reads+Writes) by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "ceil(\n  sum by (node_name) (\n    rate(\n      container_fs_reads_total{job=\"cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",kubernetes_namespace!=\"\"}[$__rate_interval]\n    )\n  + rate(\n      container_fs_writes_total{job=\"cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",kubernetes_namespace!=\"\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk  Utilization by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_free_bytes{}) by (namespace) / sum(node_filesystem_size_bytes{}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS(Reads+Writes) by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "ceil(\n  sum by (kubernetes_namespace) (\n    rate(\n      container_fs_reads_total{job=\"cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",kubernetes_namespace!=\"\"}[$__rate_interval]\n    )\n  + rate(\n      container_fs_writes_total{job=\"cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",kubernetes_namespace!=\"\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Global Network Utilization by Device",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc).*\"}[$__rate_interval])) by (device)",
     "legendFormat": "Received : {{ device }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc).*\"}[$__rate_interval])) by (device)",
     "legendFormat": "Transmitted : {{ device }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{}[$__rate_interval])) by (nic)",
     "legendFormat": "Received : {{ nic }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{}[$__rate_interval])) by (nic)",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (transmit)"
    },
    {
     "expr": "sum(rate(windows_net_packets_received_discarded_total{}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(windows_net_packets_outbound_discarded_total{}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by Node",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|lo).*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received : {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|lo).*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted : {{ instance }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{nic!~\".*Virtual.*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received : {{ instance }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{nic!~\".*Virtual.*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted : {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace) (\n  rate(\n    container_network_receive_bytes_total{}[$__rate_interval]\n  )\n)\nOR\nkube_namespace_created{} * 0",
     "legendFormat": "Received : {{ kubernetes_namespace }}"
    },
    {
     "expr": "- (sum(rate(container_network_transmit_bytes_total{}[$__rate_interval])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_network_transmit_bytes_total{container_id!=\"\"}[$__rate_interval]) * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\"}) OR kube_namespace_created{} * 0) by (namespace)))",
     "legendFormat": "Transmitted : {{ kubernetes_namespace }}"
    }
   ]
  }
 ]
}