{
 "title": "IOMETE - Spark Processing Overview Dashboard",
 "description": "This Dashboard provides overall cluster overview, not a job level",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "period", "query": "1h,3h,6h,1d,1w,4w" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(spark_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Apps Running",
   "type": "stat",
   "description": "Total running applications",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_running_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Active Drivers",
   "type": "stat",
   "description": "The amount of active drivers in the $namespace",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(metrics_executor_activeTasks{executor_id=\"driver\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Active Executors",
   "type": "bargauge",
   "description": "Total executors per application name in $namespace",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (application_name) (\n  metrics_executor_activeTasks{executor_id!=\"driver\", namespace=~\"$namespace\"}\n)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Total Active Tasks",
   "type": "bargauge",
   "description": "Total tasks per application name in $namespace",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application_name) (\n  metrics_executor_totalCores{executor_id!=\"driver\",namespace=~\"$namespace\"}\n)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Application Success Rate (%)",
   "type": "gauge",
   "description": "Application success rate within $period",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(spark_application_success_count[$period])) /\nsum(rate(spark_application_submit_count[$period])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Failure Rate Trend (Avg)",
   "type": "timeseries",
   "description": "Application Failure $period Rate Trend",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(spark_application_failure_count[$period]))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Application Success vs Failure",
   "type": "bargauge",
   "description": "Application Success vs Failure in $period",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spark_application_success_count[$period]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(spark_application_failure_count[$period]))",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Cluster Memory Usage",
   "type": "timeseries",
   "description": "Cluster instances memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(metrics_executor_memoryUsed_bytes) /\nsum(metrics_executor_maxMemory_bytes) * 100",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Overall Cluster GC Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(metrics_executor_totalGCTime_seconds_total[$period])) /\nsum(rate(metrics_executor_totalDuration_seconds_total[$period])) * 100",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Avg. App Start Latency (secs)",
   "type": "stat",
   "description": "Average Application Start Latency within $period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(spark_application_start_latency_seconds_sum[$period]) /\nrate(spark_application_start_latency_seconds_count[$period])",
     "legendFormat": "start_latency"
    }
   ]
  },
  {
   "title": "Cluster-wide I/O Pressure",
   "type": "timeseries",
   "description": "Read and Write Rates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "(sum(rate(metrics_executor_totalShuffleWrite_bytes_total[$period])) +\nsum(rate(metrics_executor_totalShuffleRead_bytes_total[$period]))) / 1024 / 1024 / 1024",
     "legendFormat": "Write+Read Rate"
    },
    {
     "expr": "sum(rate(metrics_executor_totalShuffleWrite_bytes_total[$period])) / 1024 / 1024 / 1024",
     "legendFormat": "Write Rate"
    },
    {
     "expr": "sum(rate(metrics_executor_totalShuffleRead_bytes_total[$period])) / 1024 / 1024 / 1024",
     "legendFormat": "Read Rate"
    }
   ]
  }
 ]
}