{
 "title": "IOMETE - Spark Application Metrics",
 "tags": [
  "IOMETE",
  "Spark Metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes,namespace)"
    }
   },
   {
    "name": "driver_pod",
    "label": "Driver Pod Name",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{namespace=\"$namespace\"},pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Executors Timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(metrics_executor_memoryUsed_bytes{\n  namespace=\"$namespace\", \n  executor_id!=\"driver\", \n  pod_name=\"$driver_pod\"\n}) by (application_id)",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Exec. Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalCores{namespace=\"$namespace\", pod_name=\"$driver_pod\", executor_id!=\"driver\"})"
    }
   ]
  },
  {
   "title": "Total Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_completedTasks_total{\n    namespace=\"$namespace\", \n    executor_id!=\"driver\", \n    pod_name=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_failedTasks_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\",\n    executor_id!=\"driver\"\n})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalGCTime_seconds_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "Total Storage Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_maxMemory_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "Total Input Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalInputBytes_bytes_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "Total Shuffle Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalShuffleWrite_bytes_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "Total Shuffle Read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalShuffleRead_bytes_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "RDD Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_rddBlocks{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n})"
    }
   ]
  },
  {
   "title": "Total Tasks Time per Executor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalDuration_seconds_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Tasks per Executor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalTasks_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\",\n    executor_id!=\"driver\"\n}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor GC time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalGCTime_seconds_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}[1m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Active Tasks per Executor",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "metrics_executor_activeTasks{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleRead_bytes_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleWrite_bytes_total{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_diskUsed_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Unified Memory - On-heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_OnHeapUnifiedMemory_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Unified Memory - Off-heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_OffHeapUnifiedMemory_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Storage Memory - On-heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_OnHeapStorageMemory_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Storage Memory - Off-heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_OffHeapStorageMemory_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM - On-heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_JVMHeapMemory_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM - Off-heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_JVMOffHeapMemory_bytes{\n    namespace=\"$namespace\", \n    pod_name=\"$driver_pod\"\n}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  }
 ]
}