{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    {{- include "iomete-monitoring-chart.labels" . | nindent 4}}
    app: grafana
spec:
  podSelector:
    matchLabels:
      {{- include "iomete-monitoring-chart.selectorLabels" . | nindent 6}}
      app: grafana
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow inbound web traffic
    - ports:
        - port: 3000
          protocol: TCP
      {{- if .Values.grafana.service.loadBalancerSourceRanges }}
      from:
        {{- range .Values.grafana.service.loadBalancerSourceRanges }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      {{- end }}
  egress:
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow outbound to Prometheus
    - ports:
        - port: 9090
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "iomete-monitoring-chart.selectorLabels" . | nindent 14}}
              app: prometheus
    # Allow outbound to AlertManager
    - ports:
        - port: 9093
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "iomete-monitoring-chart.selectorLabels" . | nindent 14}}
              app: alertmanager
    {{- if .Values.grafana.plugins }}
    # Allow outbound plugin downloads
    - ports:
        - port: 443
          protocol: TCP
    {{- end }}
{{- end }} 