{{- if eq .Values.grafana.storage.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
spec:
  accessModes:
    {{- range .Values.grafana.storage.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage.pvc.size }}
  {{- with include "chart.storageClassName" (dict "storageClassName" .Values.grafana.storage.pvc.storageClassName "global" .Values.global) }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
