{{- if .Values.typesenseExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-typesense-exporter
  labels:
    app: {{ .Release.Name }}-typesense-exporter
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-typesense-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-typesense-exporter
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.docker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: typesense-exporter
          image: "{{ .Values.docker.repo }}/typesense-prometheus-exporter:latest"
          imagePullPolicy: {{ .Values.docker.pullPolicy }}
          env:
            - name: TYPESENSE_API_KEY
              value: {{ .Values.typesenseExporter.settings.apiKey }}
            - name: TYPESENSE_HOST
              value: {{ .Values.typesenseExporter.settings.service }}.{{ .Values.iometeSystemNamespace }}.svc
            - name: TYPESENSE_PORT
              value: {{ .Values.typesenseExporter.settings.port | quote }}
            - name: TYPESENSE_PROTOCOL
              value: http
            - name: EXPORTER_BIND_PORT
              value: "8888"
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-typesense-exporter
  labels:
    app: {{ .Release.Name }}-typesense-exporter
spec:
  ports:
    - name: http
      port: 8888
      targetPort: http
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-typesense-exporter
{{- end }}
