apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kube-state-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iomete-monitoring-chart.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-kube-state-metrics 