apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    {{- include "iomete-monitoring-chart.labels" . | nindent 4}}
    app: prometheus
spec:
  ports:
  - port: 9090
    name: http
  selector:
    {{- include "iomete-monitoring-chart.selectorLabels" . | nindent 4}}
    app: prometheus